### ISSUE TITLE
No default application after restart

### ISSUE THREAD

**Issue by ghost** [flathub/org.gnome.Nautilus#3]
OS: Archlinux x86_64
Flatpak: 0.10.1

I'm install nautilus using flatpak vai flathub like the command below

`flatpak install --from https://flathub.org/repo/appstream/org.gnome.Nautilus.flatpakref`

Nautilus seem to work properly until i restart my pc i found nautilus unknown how to open the media applicaiton with image, audio or video file etc... I'm direct right click on video file and click open with other ... and view all application everything is empty.

Reinstall the nautilus seem to bring back the application to app list but not after when i restart my pc.

**Remark:**
1. I have some of image attachment provided. Viewing the attachment might help u clearly understand the situation.
[IMG after a first install](https://ibb.co/bYBvnw)
[IMG after reboot](https://ibb.co/jWoKEb)

2. I'm not a native English speaking. Thank you !

**Comment by csoriano1618** [comment]
Should be fixed in the new version
