### ISSUE TITLE
Update to 3.26

### ISSUE THREAD

**Issue by dsboger-zz** [flathub/org.gnome.Nautilus#4]
Could this be updated to the latest stable release? 

Also, I noticed the manifest is a bit different from the [one in the nautilus tree](https://gitlab.gnome.org/GNOME/nautilus/blob/master/build-aux/flatpak/org.gnome.Nautilus.json). The one here has `--filesystem=home`, while there it mentions `--filesystem=host`.

**Comment by csoriano1618** [comment]
Updated
